/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source code, please visit the repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MonthlyExpenseTrackerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
function getMoment(inp, format) {
  return (0, import_obsidian.moment)(inp, format);
}
var DEFAULT_SETTINGS = {
  recurringExpenses: [],
  oneTimeExpenses: [],
  monthlyPayments: [],
  monthlyNotesFolder: "Monthly Expenses",
  monthlyNoteTemplate: "# {{month}} - Monthly Expenses\n\n## Expense Tracker\n\n{{expenses}}\n\n---\n*Generated by Monthly Expense Tracker*",
  autoCreateMonthlyNotes: true,
  showStatusBar: true
};
var VIEW_TYPE_DASHBOARD = "expense-tracker-dashboard";
var MonthlyExpenseTrackerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_DASHBOARD,
      (leaf) => new DashboardView(leaf, this)
    );
    this.addRibbonIcon("wallet", "Monthly Expense Tracker", () => {
      void this.activateDashboardView();
    });
    this.addCommand({
      id: "open-expense-dashboard",
      name: "Open Expense Dashboard",
      callback: () => {
        void this.activateDashboardView();
      }
    });
    this.addCommand({
      id: "add-recurring-expense",
      name: "Add Expense",
      callback: () => {
        new AddExpenseModal(this.app, this, null).open();
      }
    });
    this.addCommand({
      id: "create-current-month-note",
      name: "Create Current Month Note",
      callback: async () => {
        const currentMonth = getMoment().format("YYYY-MM");
        await this.createMonthlyNote(currentMonth);
      }
    });
    this.addCommand({
      id: "generate-expense-report",
      name: "Generate Expense Report",
      callback: () => {
        new ReportModal(this.app, this).open();
      }
    });
    if (this.settings.showStatusBar) {
      this.statusBarItem = this.addStatusBarItem();
      this.updateStatusBar();
    }
    if (this.settings.autoCreateMonthlyNotes) {
      void this.checkAndCreateMonthlyNote();
    }
    this.addSettingTab(new ExpenseTrackerSettingTab(this.app, this));
  }
  async activateDashboardView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_DASHBOARD)[0];
    if (!leaf) {
      const newLeaf = workspace.getLeaf("tab");
      if (newLeaf) {
        await newLeaf.setViewState({
          type: VIEW_TYPE_DASHBOARD,
          active: true
        });
        leaf = newLeaf;
      }
    }
    if (leaf) {
      workspace.setActiveLeaf(leaf, { focus: true });
    }
  }
  async checkAndCreateMonthlyNote() {
    const currentMonth = getMoment().format("YYYY-MM");
    const monthlyNote = await this.getMonthlyNoteFile(currentMonth);
    if (!monthlyNote) {
      await this.createMonthlyNote(currentMonth);
    }
  }
  async ensureFolderExists(folderPath) {
    const normalizedPath = (0, import_obsidian.normalizePath)(folderPath);
    if (!normalizedPath || normalizedPath === "." || normalizedPath === "/") return;
    const parts = normalizedPath.split("/");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const normalizedCurrent = (0, import_obsidian.normalizePath)(currentPath);
      const folder = this.app.vault.getAbstractFileByPath(normalizedCurrent);
      if (!folder) {
        try {
          await this.app.vault.createFolder(normalizedCurrent);
        } catch (e) {
        }
      }
    }
  }
  async createMonthlyNote(month) {
    const folderPath = (0, import_obsidian.normalizePath)(this.settings.monthlyNotesFolder);
    const fileName = `${month}.md`;
    const filePath = (0, import_obsidian.normalizePath)(`${folderPath}/${fileName}`);
    await this.ensureFolderExists(folderPath);
    let file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian.TFile) {
      new import_obsidian.Notice(`Monthly note for ${month} already exists`);
      return file;
    }
    const expenses = this.getExpensesForMonth(month);
    const oneTimeExpenses = this.getOneTimeExpensesForMonth(month);
    const prevMonth = getMoment(month, "YYYY-MM").subtract(1, "month").format("YYYY-MM");
    const unpaidFromPrev = this.getUnpaidExpenses(prevMonth);
    let expenseList = "## Recurring Expenses\n\n";
    expenses.forEach((expense) => {
      const payment = this.getPayment(expense.id, month);
      const status = (payment == null ? void 0 : payment.paid) ? "x" : " ";
      const statusIcon = (payment == null ? void 0 : payment.paid) ? "\u2705" : "\u2B1C";
      const cur = expense.currency || "USD";
      let symbol = cur + " ";
      if (cur === "USD") symbol = "$";
      else if (cur === "BOB") symbol = "Bs ";
      else if (cur === "EUR") symbol = "\u20AC";
      else if (cur === "GBP") symbol = "\xA3";
      expenseList += `- [${status}] ${statusIcon} **${expense.name}** - ${symbol}${expense.amount.toFixed(2)} - Due: ${expense.dueDay} - Method: ${expense.paymentMethod}
`;
      expenseList += `  - ID: \`${expense.id}\`
`;
      if (payment == null ? void 0 : payment.confirmationNumber) {
        expenseList += `  - Confirmation: ${payment.confirmationNumber}
`;
      }
      expenseList += "\n";
    });
    if (oneTimeExpenses.length > 0) {
      expenseList += "## One-Time Expenses\n\n";
      oneTimeExpenses.forEach((expense) => {
        const status = expense.paid ? "x" : " ";
        const statusIcon = expense.paid ? "\u2705" : "\u2B1C";
        const cur = expense.currency || "USD";
        let symbol = cur + " ";
        if (cur === "USD") symbol = "$";
        else if (cur === "BOB") symbol = "Bs ";
        else if (cur === "EUR") symbol = "\u20AC";
        else if (cur === "GBP") symbol = "\xA3";
        expenseList += `- [${status}] ${statusIcon} **${expense.name}** - ${symbol}${expense.amount.toFixed(2)} - Date: ${expense.date} - Method: ${expense.paymentMethod}
`;
        expenseList += `  - ID: \`${expense.id}\`
`;
        if (expense.confirmationNumber) {
          expenseList += `  - Confirmation: ${expense.confirmationNumber}
`;
        }
        expenseList += "\n";
      });
    }
    if (unpaidFromPrev.length > 0) {
      expenseList += "\n## Unpaid from Previous Month\n\n";
      unpaidFromPrev.forEach((expense) => {
        const symbol = (expense.currency || "USD") === "USD" ? "$" : (expense.currency || "USD") === "BOB" ? "Bs " : `${expense.currency} `;
        expenseList += `- [ ] \u26A0\uFE0F **${expense.name}** - ${symbol}${expense.amount.toFixed(2)} - OVERDUE
`;
        expenseList += `  - ID: \`${expense.id}\`

`;
      });
    }
    if (expenses.length === 0 && oneTimeExpenses.length === 0) {
      expenseList += '\n*No expenses set up for this month yet. Click "**+ Add Expense**" in the dashboard to add expenses.*\n\n';
    }
    const content = this.settings.monthlyNoteTemplate.replace("{{month}}", getMoment(month, "YYYY-MM").format("MMMM YYYY")).replace("{{expenses}}", expenseList);
    const newFile = await this.app.vault.create(filePath, content);
    new import_obsidian.Notice(`Created monthly note for ${month}`);
    return newFile;
  }
  async getMonthlyNoteFile(month) {
    const filePath = (0, import_obsidian.normalizePath)(`${this.settings.monthlyNotesFolder}/${month}.md`);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    return file instanceof import_obsidian.TFile ? file : null;
  }
  getExpensesForMonth(month) {
    return this.settings.recurringExpenses.filter((expense) => {
      if (expense.archived) return false;
      const expenseStart = getMoment(expense.startDate, "YYYY-MM");
      const expenseEnd = expense.endDate ? getMoment(expense.endDate, "YYYY-MM") : null;
      const checkMonth = getMoment(month, "YYYY-MM");
      const afterStart = checkMonth.isSameOrAfter(expenseStart);
      const beforeEnd = !expenseEnd || checkMonth.isSameOrBefore(expenseEnd);
      return afterStart && beforeEnd;
    });
  }
  getUnpaidExpenses(month) {
    const expenses = this.getExpensesForMonth(month);
    return expenses.filter((expense) => {
      const payment = this.getPayment(expense.id, month);
      return !payment || !payment.paid;
    });
  }
  getPayment(expenseId, month) {
    return this.settings.monthlyPayments.find(
      (p) => p.expenseId === expenseId && p.month === month
    );
  }
  async markExpensePaid(expenseId, month, paid, confirmationNumber) {
    const existingPayment = this.getPayment(expenseId, month);
    if (existingPayment) {
      existingPayment.paid = paid;
      existingPayment.paidDate = paid ? getMoment().format("YYYY-MM-DD") : void 0;
      existingPayment.confirmationNumber = confirmationNumber;
    } else {
      this.settings.monthlyPayments.push({
        expenseId,
        month,
        paid,
        paidDate: paid ? getMoment().format("YYYY-MM-DD") : void 0,
        confirmationNumber
      });
    }
    await this.saveSettings();
    this.updateStatusBar();
  }
  async addRecurringExpense(expense) {
    this.settings.recurringExpenses.push(expense);
    await this.saveSettings();
    new import_obsidian.Notice(`Added recurring expense: ${expense.name}`);
  }
  async addOneTimeExpense(expense) {
    this.settings.oneTimeExpenses.push(expense);
    await this.saveSettings();
    new import_obsidian.Notice(`Added one-time expense: ${expense.name}`);
  }
  getOneTimeExpensesForMonth(month) {
    return this.settings.oneTimeExpenses.filter((expense) => {
      const expenseDate = getMoment(expense.date);
      return expenseDate.format("YYYY-MM") === month;
    });
  }
  async markOneTimeExpensePaid(expenseId, paid, confirmationNumber) {
    const expense = this.settings.oneTimeExpenses.find((e) => e.id === expenseId);
    if (expense) {
      expense.paid = paid;
      expense.paidDate = paid ? getMoment().format("YYYY-MM-DD") : void 0;
      if (confirmationNumber) expense.confirmationNumber = confirmationNumber;
      await this.saveSettings();
      this.updateStatusBar();
    }
  }
  async updateOneTimeExpense(expense) {
    const index = this.settings.oneTimeExpenses.findIndex((e) => e.id === expense.id);
    if (index !== -1) {
      this.settings.oneTimeExpenses[index] = expense;
      await this.saveSettings();
      new import_obsidian.Notice(`Updated expense: ${expense.name}`);
    }
  }
  async deleteOneTimeExpense(expenseId) {
    this.settings.oneTimeExpenses = this.settings.oneTimeExpenses.filter((e) => e.id !== expenseId);
    await this.saveSettings();
    new import_obsidian.Notice("Expense deleted");
  }
  async updateRecurringExpense(expense) {
    const index = this.settings.recurringExpenses.findIndex((e) => e.id === expense.id);
    if (index !== -1) {
      this.settings.recurringExpenses[index] = expense;
      await this.saveSettings();
      new import_obsidian.Notice(`Updated expense: ${expense.name}`);
    }
  }
  async archiveExpense(expenseId) {
    const expense = this.settings.recurringExpenses.find((e) => e.id === expenseId);
    if (expense) {
      expense.archived = true;
      await this.saveSettings();
      new import_obsidian.Notice(`Archived expense: ${expense.name}`);
    }
  }
  async deleteExpense(expenseId) {
    this.settings.recurringExpenses = this.settings.recurringExpenses.filter((e) => e.id !== expenseId);
    this.settings.monthlyPayments = this.settings.monthlyPayments.filter((p) => p.expenseId !== expenseId);
    await this.saveSettings();
    new import_obsidian.Notice("Expense deleted");
  }
  updateStatusBar() {
    if (!this.statusBarItem) return;
    const currentMonth = getMoment().format("YYYY-MM");
    const unpaid = this.getUnpaidExpenses(currentMonth);
    const recurringTotal = this.getExpensesForMonth(currentMonth).length;
    const oneTime = this.getOneTimeExpensesForMonth(currentMonth);
    const oneTimeUnpaid = oneTime.filter((e) => !e.paid);
    const totalUnpaidCount = unpaid.length + oneTimeUnpaid.length;
    const totalCount = recurringTotal + oneTime.length;
    if (totalUnpaidCount > 0) {
      this.statusBarItem.textContent = `\u{1F4B3} ${totalUnpaidCount}/${totalCount} unpaid`;
      this.statusBarItem.classList.add("expense-tracker-unpaid");
    } else if (totalCount > 0) {
      this.statusBarItem.textContent = `\u{1F4B3} All paid`;
      this.statusBarItem.classList.remove("expense-tracker-unpaid");
    } else {
      this.statusBarItem.textContent = "\u{1F4B3}";
    }
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData || {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_DASHBOARD);
    leaves.forEach((leaf) => {
      if (leaf.view instanceof DashboardView) {
        leaf.view.refresh();
      }
    });
  }
  onunload() {
  }
};
var DashboardView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.currentMonth = getMoment().format("YYYY-MM");
  }
  getViewType() {
    return VIEW_TYPE_DASHBOARD;
  }
  getDisplayText() {
    return "Expense Dashboard";
  }
  getIcon() {
    return "wallet";
  }
  async onOpen() {
    this.refresh();
  }
  refresh() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("expense-tracker-dashboard");
    const header = container.createDiv("expense-tracker-header");
    header.createEl("h2", { text: "Monthly Expense Tracker" });
    const monthSelector = container.createDiv("expense-tracker-month-selector");
    const prevBtn = monthSelector.createEl("button", { text: "\u25C0" });
    prevBtn.onclick = () => {
      this.currentMonth = getMoment(this.currentMonth, "YYYY-MM").subtract(1, "month").format("YYYY-MM");
      this.refresh();
    };
    monthSelector.createSpan({
      text: getMoment(this.currentMonth, "YYYY-MM").format("MMMM YYYY"),
      cls: "expense-tracker-month-display"
    });
    const nextBtn = monthSelector.createEl("button", { text: "\u25B6" });
    nextBtn.onclick = () => {
      this.currentMonth = getMoment(this.currentMonth, "YYYY-MM").add(1, "month").format("YYYY-MM");
      this.refresh();
    };
    const todayBtn = monthSelector.createEl("button", { text: "Today" });
    todayBtn.onclick = () => {
      this.currentMonth = getMoment().format("YYYY-MM");
      this.refresh();
    };
    const recurringExpenses = this.plugin.getExpensesForMonth(this.currentMonth);
    const oneTimeExpenses = this.plugin.getOneTimeExpensesForMonth(this.currentMonth);
    const totals = {};
    let totalCount = 0;
    let totalUnpaidCount = 0;
    const processExpense = (amount, currency, paid) => {
      if (!totals[currency]) totals[currency] = { total: 0, paid: 0, unpaidCount: 0 };
      totals[currency].total += amount;
      if (paid) {
        totals[currency].paid += amount;
      } else {
        totals[currency].unpaidCount++;
        totalUnpaidCount++;
      }
      totalCount++;
    };
    recurringExpenses.forEach((e) => {
      const payment = this.plugin.getPayment(e.id, this.currentMonth);
      const isPaid = (payment == null ? void 0 : payment.paid) || false;
      processExpense(e.amount, e.currency || "USD", isPaid);
    });
    oneTimeExpenses.forEach((e) => {
      processExpense(e.amount, e.currency || "USD", e.paid);
    });
    const summary = container.createDiv("expense-tracker-summary");
    const statItem1 = summary.createDiv("expense-tracker-summary-item");
    statItem1.createSpan({ text: "Total Expenses:", cls: "expense-tracker-summary-label" });
    statItem1.createSpan({ text: totalCount.toString(), cls: "expense-tracker-summary-value" });
    const statItem2 = summary.createDiv("expense-tracker-summary-item");
    statItem2.createSpan({ text: "Unpaid Count:", cls: "expense-tracker-summary-label" });
    const unpaidSpan = statItem2.createSpan({ text: totalUnpaidCount.toString(), cls: "expense-tracker-summary-value unpaid" });
    if (totalUnpaidCount > 0) unpaidSpan.addClass("unpaid");
    const currencies = Object.keys(totals).sort();
    if (currencies.length === 0) {
      const statItemEmpty = summary.createDiv("expense-tracker-summary-item");
      statItemEmpty.createSpan({ text: "Total Amount:", cls: "expense-tracker-summary-label" });
      statItemEmpty.createSpan({ text: "$0.00", cls: "expense-tracker-summary-value" });
    } else {
      const totalsDiv = container.createDiv("expense-tracker-summary-totals");
      currencies.forEach((currency) => {
        let symbol = currency + " ";
        if (currency === "USD") symbol = "$";
        else if (currency === "BOB") symbol = "Bs ";
        else if (currency === "EUR") symbol = "\u20AC";
        else if (currency === "GBP") symbol = "\xA3";
        const data = totals[currency];
        const row = totalsDiv.createDiv("expense-tracker-currency-row");
        row.createSpan({ text: currency, cls: "expense-tracker-currency-label" });
        row.createSpan({ text: `Total: ${symbol}${data.total.toFixed(2)}` });
        row.createSpan({ text: `Paid: ${symbol}${data.paid.toFixed(2)}`, cls: "paid" });
        row.createSpan({ text: `Unpaid: ${symbol}${(data.total - data.paid).toFixed(2)}`, cls: "unpaid" });
      });
    }
    const actions = container.createDiv("expense-tracker-actions");
    const addBtn = actions.createEl("button", { text: "+ Add Expense", cls: "mod-cta" });
    addBtn.onclick = () => {
      new AddExpenseModal(this.app, this.plugin, null).open();
    };
    const createNoteBtn = actions.createEl("button", { text: "\u{1F4C4} Create Monthly Note" });
    createNoteBtn.onclick = async () => {
      await this.plugin.createMonthlyNote(this.currentMonth);
    };
    const reportBtn = actions.createEl("button", { text: "\u{1F4CA} Generate Report" });
    reportBtn.onclick = () => {
      new ReportModal(this.app, this.plugin).open();
    };
    const supportBtn = actions.createEl("button", { text: "\u{1F499} Support Plugin", cls: "mod-cta" });
    supportBtn.onclick = () => {
      new SupportModal(this.app).open();
    };
    const expenseList = container.createDiv("expense-tracker-list");
    if (totalCount === 0) {
      expenseList.createDiv("expense-tracker-empty").setText("No expenses for this month");
    } else {
      if (totalUnpaidCount > 0) {
        expenseList.createEl("h3", { text: "Unpaid" });
        recurringExpenses.filter((e) => {
          const payment = this.plugin.getPayment(e.id, this.currentMonth);
          return !(payment == null ? void 0 : payment.paid);
        }).forEach((expense) => {
          this.renderRecurringExpenseItem(expenseList, expense);
        });
        oneTimeExpenses.filter((e) => !e.paid).forEach((expense) => {
          this.renderOneTimeExpenseItem(expenseList, expense);
        });
      }
      if (totalCount - totalUnpaidCount > 0) {
        expenseList.createEl("h3", { text: "Paid" });
        recurringExpenses.filter((e) => {
          const payment = this.plugin.getPayment(e.id, this.currentMonth);
          return payment == null ? void 0 : payment.paid;
        }).forEach((expense) => {
          this.renderRecurringExpenseItem(expenseList, expense);
        });
        oneTimeExpenses.filter((e) => e.paid).forEach((expense) => {
          this.renderOneTimeExpenseItem(expenseList, expense);
        });
      }
    }
    const archivedExpenses = this.plugin.settings.recurringExpenses.filter((e) => e.archived);
    if (archivedExpenses.length > 0) {
      const archivedSection = container.createDiv("expense-tracker-archived");
      const archivedHeader = archivedSection.createEl("h3", { text: "Archived Expenses", cls: "expense-tracker-archived-header" });
      const archivedList = archivedSection.createDiv("expense-tracker-archived-list is-hidden");
      archivedHeader.onclick = () => {
        archivedList.toggleClass("is-hidden", !archivedList.hasClass("is-hidden"));
      };
      archivedExpenses.forEach((expense) => {
        const item = archivedList.createDiv("expense-tracker-item archived");
        item.createDiv({ cls: "expense-tracker-item-name", text: expense.name });
        const currencySymbol = expense.currency === "USD" ? "$" : expense.currency === "BOB" ? "Bs " : expense.currency + " ";
        item.createDiv({ cls: "expense-tracker-item-details", text: `${currencySymbol}${expense.amount.toFixed(2)} - ${expense.paymentMethod}` });
        item.onclick = (e) => {
          const menu = new import_obsidian.Menu();
          menu.addItem((item2) => {
            item2.setTitle("Unarchive").onClick(async () => {
              expense.archived = false;
              await this.plugin.saveSettings();
              this.refresh();
            });
          });
          menu.addItem((item2) => {
            item2.setTitle("Delete").onClick(async () => {
              await this.plugin.deleteExpense(expense.id);
              this.refresh();
            });
          });
          menu.showAtMouseEvent(e);
        };
      });
    }
  }
  renderRecurringExpenseItem(container, expense) {
    const payment = this.plugin.getPayment(expense.id, this.currentMonth);
    const isPaid = (payment == null ? void 0 : payment.paid) || false;
    const isOverdue = expense.dueDay < parseInt(getMoment().format("D")) && !isPaid && this.currentMonth === getMoment().format("YYYY-MM");
    const item = container.createDiv("expense-tracker-item");
    if (isPaid) item.addClass("paid");
    if (isOverdue) item.addClass("overdue");
    const checkbox = item.createEl("input", { type: "checkbox" });
    checkbox.checked = isPaid;
    checkbox.onclick = async (e) => {
      e.stopPropagation();
      if (!isPaid) {
        new MarkPaidModal(this.app, this.plugin, expense, this.currentMonth, () => {
          this.refresh();
        }).open();
      } else {
        await this.plugin.markExpensePaid(expense.id, this.currentMonth, false);
        this.refresh();
      }
    };
    const content = item.createDiv("expense-tracker-item-content");
    const nameDiv = content.createDiv("expense-tracker-item-name");
    nameDiv.setText(expense.name);
    if (isOverdue) {
      nameDiv.createSpan({ text: " \u26A0\uFE0F OVERDUE", cls: "expense-tracker-overdue-badge" });
    }
    const details = content.createDiv("expense-tracker-item-details");
    const symbol = (expense.currency || "USD") === "USD" ? "$" : (expense.currency || "USD") === "BOB" ? "Bs " : `${expense.currency} `;
    details.setText(`${symbol}${expense.amount.toFixed(2)} \u2022 Due: ${expense.dueDay} \u2022 ${expense.paymentMethod}`);
    if (payment == null ? void 0 : payment.confirmationNumber) {
      details.createDiv({ text: `Confirmation: ${payment.confirmationNumber}` });
    }
    if (payment == null ? void 0 : payment.paidDate) {
      details.createDiv({ text: `Paid: ${payment.paidDate}` });
    }
    const actions = item.createDiv("expense-tracker-item-actions");
    this.addContextMenu(actions, expense, "recurring");
  }
  renderOneTimeExpenseItem(container, expense) {
    const isPaid = expense.paid;
    const expenseDate = getMoment(expense.date);
    const isOverdue = expenseDate.isBefore(getMoment(), "day") && !isPaid;
    const item = container.createDiv("expense-tracker-item");
    if (isPaid) item.addClass("paid");
    if (isOverdue) item.addClass("overdue");
    const checkbox = item.createEl("input", { type: "checkbox" });
    checkbox.checked = isPaid;
    checkbox.onclick = async (e) => {
      e.stopPropagation();
      if (!isPaid) {
        await this.plugin.markOneTimeExpensePaid(expense.id, true);
        this.refresh();
      } else {
        await this.plugin.markOneTimeExpensePaid(expense.id, false);
        this.refresh();
      }
    };
    const content = item.createDiv("expense-tracker-item-content");
    const nameDiv = content.createDiv("expense-tracker-item-name");
    nameDiv.setText(expense.name);
    nameDiv.createSpan({ text: " (One-Time)", cls: "expense-tracker-type-badge" });
    if (isOverdue) {
      nameDiv.createSpan({ text: " \u26A0\uFE0F OVERDUE", cls: "expense-tracker-overdue-badge" });
    }
    const details = content.createDiv("expense-tracker-item-details");
    const symbol = (expense.currency || "USD") === "USD" ? "$" : (expense.currency || "USD") === "BOB" ? "Bs " : `${expense.currency} `;
    details.setText(`${symbol}${expense.amount.toFixed(2)} \u2022 Date: ${expense.date} \u2022 ${expense.paymentMethod}`);
    if (expense.confirmationNumber) {
      details.createDiv({ text: `Confirmation: ${expense.confirmationNumber}` });
    }
    if (expense.paidDate) {
      details.createDiv({ text: `Paid: ${expense.paidDate}` });
    }
    const actions = item.createDiv("expense-tracker-item-actions");
    this.addContextMenu(actions, expense, "onetime");
  }
  addContextMenu(container, expense, type) {
    const menuBtn = container.createEl("button", { text: "\u22EE" });
    menuBtn.onclick = (e) => {
      e.stopPropagation();
      const menu = new import_obsidian.Menu();
      menu.addItem((item) => {
        item.setTitle("Edit").setIcon("pencil").onClick(() => {
          new AddExpenseModal(this.app, this.plugin, expense).open();
        });
      });
      if (type === "recurring") {
        menu.addItem((item) => {
          item.setTitle("View History").setIcon("history").onClick(() => {
            new HistoryModal(this.app, this.plugin, expense).open();
          });
        });
        menu.addItem((item) => {
          item.setTitle("Archive").setIcon("archive").onClick(async () => {
            await this.plugin.archiveExpense(expense.id);
            this.refresh();
          });
        });
        menu.addItem((item) => {
          item.setTitle("Delete").setIcon("trash").onClick(async () => {
            await this.plugin.deleteExpense(expense.id);
            this.refresh();
          });
        });
      } else {
        menu.addItem((item) => {
          item.setTitle("Delete").setIcon("trash").onClick(async () => {
            await this.plugin.deleteOneTimeExpense(expense.id);
            this.refresh();
          });
        });
      }
      menu.showAtMouseEvent(e);
    };
  }
  async onClose() {
  }
};
var AddExpenseModal = class extends import_obsidian.Modal {
  constructor(app, plugin, expense) {
    super(app);
    this.plugin = plugin;
    if (expense && "date" in expense) {
      this.oneTimeExpense = expense;
      this.expense = null;
      this.type = "onetime";
    } else {
      this.expense = expense;
      this.oneTimeExpense = null;
      this.type = "recurring";
    }
  }
  onOpen() {
    var _a, _b;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.expense || this.oneTimeExpense ? "Edit Expense" : "Add Expense" });
    const form = contentEl.createDiv("expense-tracker-form");
    if (!this.expense && !this.oneTimeExpense) {
      new import_obsidian.Setting(form).setName("Expense Type").addDropdown((dropdown) => {
        dropdown.addOption("recurring", "Recurring (Monthly)").addOption("onetime", "One-Time").setValue(this.type).onChange(async (value) => {
          this.type = value;
          this.onOpen();
        });
      });
    }
    new import_obsidian.Setting(form).setName("Expense Name").addText((text) => {
      var _a2, _b2;
      text.setValue(((_a2 = this.expense) == null ? void 0 : _a2.name) || ((_b2 = this.oneTimeExpense) == null ? void 0 : _b2.name) || "");
      text.inputEl.id = "expense-name";
    });
    new import_obsidian.Setting(form).setName("Currency").addDropdown((dropdown) => {
      var _a2, _b2, _c, _d;
      dropdown.addOption("USD", "USD ($)").addOption("BOB", "BOB (Bs)").addOption("EUR", "EUR (\u20AC)").addOption("GBP", "GBP (\xA3)").addOption("OTHER", "Other (Custom)").setValue(
        ["USD", "BOB", "EUR", "GBP"].includes(((_a2 = this.expense) == null ? void 0 : _a2.currency) || ((_b2 = this.oneTimeExpense) == null ? void 0 : _b2.currency) || "USD") ? ((_c = this.expense) == null ? void 0 : _c.currency) || ((_d = this.oneTimeExpense) == null ? void 0 : _d.currency) || "USD" : "OTHER"
      );
      dropdown.selectEl.id = "expense-currency-select";
      dropdown.onChange((value) => {
        const customInput = document.getElementById("expense-currency-custom-container");
        if (customInput) {
          customInput.style.display = value === "OTHER" ? "block" : "none";
        }
      });
    });
    const customCurrencyDiv = form.createDiv();
    customCurrencyDiv.id = "expense-currency-custom-container";
    customCurrencyDiv.style.display = ["USD", "BOB", "EUR", "GBP"].includes(((_a = this.expense) == null ? void 0 : _a.currency) || ((_b = this.oneTimeExpense) == null ? void 0 : _b.currency) || "USD") ? "none" : "block";
    new import_obsidian.Setting(customCurrencyDiv).setName("Custom Currency Code").setDesc("e.g., CAD, JPY, AUD").addText((text) => {
      var _a2, _b2;
      const current = ((_a2 = this.expense) == null ? void 0 : _a2.currency) || ((_b2 = this.oneTimeExpense) == null ? void 0 : _b2.currency) || "USD";
      text.setValue(["USD", "BOB", "EUR", "GBP"].includes(current) ? "" : current);
      text.inputEl.id = "expense-currency-custom";
    });
    new import_obsidian.Setting(form).setName("Amount").addText((text) => {
      var _a2, _b2;
      text.setValue(((_a2 = this.expense) == null ? void 0 : _a2.amount.toString()) || ((_b2 = this.oneTimeExpense) == null ? void 0 : _b2.amount.toString()) || "");
      text.inputEl.type = "number";
      text.inputEl.step = "0.01";
      text.inputEl.id = "expense-amount";
    });
    if (this.type === "recurring") {
      new import_obsidian.Setting(form).setName("Due Day of Month").setDesc("1-31").addText((text) => {
        var _a2;
        text.setValue(((_a2 = this.expense) == null ? void 0 : _a2.dueDay.toString()) || "1");
        text.inputEl.type = "number";
        text.inputEl.min = "1";
        text.inputEl.max = "31";
        text.inputEl.id = "expense-due-day";
      });
      new import_obsidian.Setting(form).setName("Start Month").setDesc("YYYY-MM format").addText((text) => {
        var _a2;
        text.setValue(((_a2 = this.expense) == null ? void 0 : _a2.startDate) || getMoment().format("YYYY-MM"));
        text.inputEl.id = "expense-start-date";
      });
      new import_obsidian.Setting(form).setName("End Month (Optional)").setDesc("YYYY-MM format - leave empty for ongoing").addText((text) => {
        var _a2;
        text.setValue(((_a2 = this.expense) == null ? void 0 : _a2.endDate) || "");
        text.inputEl.id = "expense-end-date";
      });
    } else {
      new import_obsidian.Setting(form).setName("Date").setDesc("YYYY-MM-DD format").addText((text) => {
        var _a2;
        text.setValue(((_a2 = this.oneTimeExpense) == null ? void 0 : _a2.date) || getMoment().format("YYYY-MM-DD"));
        text.inputEl.type = "date";
        text.inputEl.id = "expense-date";
      });
    }
    new import_obsidian.Setting(form).setName("Payment Method").addText((text) => {
      var _a2, _b2;
      text.setValue(((_a2 = this.expense) == null ? void 0 : _a2.paymentMethod) || ((_b2 = this.oneTimeExpense) == null ? void 0 : _b2.paymentMethod) || "");
      text.inputEl.id = "expense-payment-method";
    });
    new import_obsidian.Setting(form).setName("Category (Optional)").addText((text) => {
      var _a2, _b2;
      text.setValue(((_a2 = this.expense) == null ? void 0 : _a2.category) || ((_b2 = this.oneTimeExpense) == null ? void 0 : _b2.category) || "");
      text.inputEl.id = "expense-category";
    });
    const buttonDiv = contentEl.createDiv("expense-tracker-modal-button-container");
    const saveBtn = buttonDiv.createEl("button", { text: "Save", cls: "mod-cta" });
    saveBtn.onclick = async () => {
      await this.handleSubmit();
    };
    const cancelBtn = buttonDiv.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => {
      this.close();
    };
  }
  async handleSubmit() {
    var _a, _b, _c, _d, _e, _f;
    const name = document.getElementById("expense-name").value;
    let currency = document.getElementById("expense-currency-select").value;
    if (currency === "OTHER") {
      currency = document.getElementById("expense-currency-custom").value.toUpperCase();
      if (!currency) {
        new import_obsidian.Notice("Please enter a custom currency code");
        return;
      }
    }
    const amount = parseFloat(document.getElementById("expense-amount").value);
    const paymentMethod = document.getElementById("expense-payment-method").value;
    const category = document.getElementById("expense-category").value;
    if (!name || isNaN(amount) || !paymentMethod) {
      new import_obsidian.Notice("Please fill in all required fields");
      return;
    }
    if (this.type === "recurring") {
      const dueDayStr = document.getElementById("expense-due-day").value;
      const startDate = document.getElementById("expense-start-date").value;
      const endDate = document.getElementById("expense-end-date").value;
      const dueDay = parseInt(dueDayStr);
      if (!dueDay || !startDate) {
        new import_obsidian.Notice("Please fill in all required fields for recurring expense");
        return;
      }
      const expense = {
        id: ((_a = this.expense) == null ? void 0 : _a.id) || `exp-${Date.now()}`,
        name,
        amount,
        currency,
        dueDay,
        paymentMethod,
        startDate,
        endDate: endDate || void 0,
        category: category || void 0,
        archived: ((_b = this.expense) == null ? void 0 : _b.archived) || false
      };
      if (this.expense) {
        await this.plugin.updateRecurringExpense(expense);
      } else {
        await this.plugin.addRecurringExpense(expense);
      }
    } else {
      const date = document.getElementById("expense-date").value;
      if (!date) {
        new import_obsidian.Notice("Please select a date for the one-time expense");
        return;
      }
      const expense = {
        id: ((_c = this.oneTimeExpense) == null ? void 0 : _c.id) || `one-${Date.now()}`,
        name,
        amount,
        currency,
        date,
        paymentMethod,
        category: category || void 0,
        paid: ((_d = this.oneTimeExpense) == null ? void 0 : _d.paid) || false,
        paidDate: (_e = this.oneTimeExpense) == null ? void 0 : _e.paidDate,
        confirmationNumber: (_f = this.oneTimeExpense) == null ? void 0 : _f.confirmationNumber
      };
      if (this.oneTimeExpense) {
        await this.plugin.updateOneTimeExpense(expense);
      } else {
        await this.plugin.addOneTimeExpense(expense);
      }
    }
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var MarkPaidModal = class extends import_obsidian.Modal {
  constructor(app, plugin, expense, month, onComplete) {
    super(app);
    this.plugin = plugin;
    this.expense = expense;
    this.month = month;
    this.onComplete = onComplete;
    this.isOneTime = "date" in expense;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Mark as Paid" });
    contentEl.createEl("p", { text: `${this.expense.name} - $${this.expense.amount.toFixed(2)}` });
    const form = contentEl.createDiv();
    new import_obsidian.Setting(form).setName("Confirmation Number (Optional)").addText((text) => {
      text.inputEl.id = "confirmation-number";
    });
    const buttonDiv = contentEl.createDiv("expense-tracker-modal-button-container");
    const saveBtn = buttonDiv.createEl("button", { text: "Mark Paid", cls: "mod-cta" });
    saveBtn.onclick = async () => {
      const confirmationNumber = document.getElementById("confirmation-number").value;
      if (this.isOneTime) {
        await this.plugin.markOneTimeExpensePaid(this.expense.id, true, confirmationNumber || void 0);
      } else {
        await this.plugin.markExpensePaid(this.expense.id, this.month, true, confirmationNumber || void 0);
      }
      this.onComplete();
      this.close();
    };
    const cancelBtn = buttonDiv.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => {
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var HistoryModal = class extends import_obsidian.Modal {
  constructor(app, plugin, expense) {
    super(app);
    this.plugin = plugin;
    this.expense = expense;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: `Payment History: ${this.expense.name}` });
    const history = this.plugin.settings.monthlyPayments.filter((p) => p.expenseId === this.expense.id).sort((a, b) => b.month.localeCompare(a.month));
    if (history.length === 0) {
      contentEl.createEl("p", { text: "No payment history" });
    } else {
      const table = contentEl.createEl("table", { cls: "expense-tracker-history-table" });
      const thead = table.createEl("thead");
      const headerRow = thead.createEl("tr");
      headerRow.createEl("th", { text: "Month" });
      headerRow.createEl("th", { text: "Status" });
      headerRow.createEl("th", { text: "Paid Date" });
      headerRow.createEl("th", { text: "Confirmation" });
      const tbody = table.createEl("tbody");
      history.forEach((payment) => {
        const row = tbody.createEl("tr");
        row.createEl("td", { text: getMoment(payment.month, "YYYY-MM").format("MMM YYYY") });
        row.createEl("td", { text: payment.paid ? "\u2705 Paid" : "\u2B1C Unpaid" });
        row.createEl("td", { text: payment.paidDate || "-" });
        row.createEl("td", { text: payment.confirmationNumber || "-" });
      });
    }
    const closeBtn = contentEl.createEl("button", { text: "Close" });
    closeBtn.onclick = () => this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var SupportModal = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("expense-tracker-support-modal");
    contentEl.createEl("h2", { text: "\u{1F499} Support Monthly Expense Tracker", cls: "expense-tracker-support-header" });
    contentEl.createEl("p", {
      text: "Thank you for considering supporting this plugin! Your support helps maintain and improve this tool."
    });
    const paypalSection = contentEl.createDiv("expense-tracker-support-section");
    paypalSection.createEl("h3", { text: "\u{1F4B3} PayPal" });
    paypalSection.createEl("p", { text: "One-time or recurring donations via PayPal:" });
    paypalSection.createEl("a", {
      text: "\u2192 Donate via PayPal",
      href: "https://www.paypal.com/paypalme/VictorZenteno",
      cls: "expense-tracker-support-link"
    });
    const cryptoSection = contentEl.createDiv("expense-tracker-support-section");
    cryptoSection.createEl("h3", { text: "\u{1FA99} Cryptocurrency (USDC/USDT)" });
    cryptoSection.createEl("p", { text: "Support with stablecoins on multiple networks:" });
    const cryptoAddresses = cryptoSection.createDiv("expense-tracker-crypto-addresses");
    const usdcDiv = cryptoAddresses.createDiv("expense-tracker-crypto-address");
    usdcDiv.createEl("strong", { text: "USDC (Base Network - Low Fees):" });
    usdcDiv.createEl("code", { text: "0x1023142d0548b63542f2a4803b6724d4c26b8bda", cls: "expense-tracker-code-block" });
    usdcDiv.createEl("small", { text: "Also works on: Ethereum, Polygon, Arbitrum, Optimism", cls: "expense-tracker-note" });
    const usdtDiv = cryptoAddresses.createDiv("expense-tracker-crypto-address");
    usdtDiv.createEl("strong", { text: "USDT (Tron TRC-20 - Ultra Low Fees):" });
    usdtDiv.createEl("code", { text: "TAV7qTGgvn8GnYJfXfes73tD2dAPQJ3L2W", cls: "expense-tracker-code-block" });
    cryptoSection.createEl("p", { text: "\u26A0\uFE0F Important: Double-check the network before sending!", cls: "expense-tracker-text-error" });
    cryptoSection.createEl("p", { text: "\u{1F4A1} Tip: Use Tron for USDT or Base for USDC to minimize fees!", cls: "expense-tracker-text-muted" });
    const coffeeSection = contentEl.createDiv("expense-tracker-support-section");
    coffeeSection.createEl("h3", { text: "\u2615 Buy Me a Coffee" });
    coffeeSection.createEl("p", { text: "Simple, friendly way to support:" });
    coffeeSection.createEl("a", {
      text: "\u2192 Buy Me a Coffee",
      href: "https://buymeacoffee.com/rvzen",
      cls: "expense-tracker-support-link"
    });
    const otherSection = contentEl.createDiv("expense-tracker-support-section");
    otherSection.createEl("h3", { text: "\u{1F31F} Other Ways to Support" });
    const otherList = otherSection.createEl("ul");
    otherList.createEl("li", { text: "\u2B50 Star the GitHub repository" });
    otherList.createEl("li", { text: "\u{1F41B} Report bugs and issues" });
    otherList.createEl("li", { text: "\u{1F4A1} Suggest new features" });
    otherList.createEl("li", { text: "\u{1F4DD} Improve documentation" });
    otherList.createEl("li", { text: "\u{1F5E3}\uFE0F Tell others about the plugin" });
    const footer = contentEl.createDiv("expense-tracker-support-footer-box");
    footer.createEl("p", { text: "Thank you for your support! \u{1F64F}" });
    footer.createEl("small", { text: "All donations help maintain and improve this plugin" });
    const closeBtn = contentEl.createEl("button", { text: "Close", cls: "expense-tracker-btn-full" });
    closeBtn.onclick = () => this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ReportModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Expense Report" });
    const form = contentEl.createDiv();
    new import_obsidian.Setting(form).setName("Start Month").setDesc("YYYY-MM format").addText((text) => {
      text.setValue(getMoment().subtract(5, "months").format("YYYY-MM"));
      text.inputEl.id = "report-start";
    });
    new import_obsidian.Setting(form).setName("End Month").setDesc("YYYY-MM format").addText((text) => {
      text.setValue(getMoment().format("YYYY-MM"));
      text.inputEl.id = "report-end";
    });
    const buttonDiv = contentEl.createDiv("modal-button-container");
    const generateBtn = buttonDiv.createEl("button", { text: "Generate", cls: "mod-cta" });
    generateBtn.onclick = () => {
      void this.generateReport();
    };
    const cancelBtn = buttonDiv.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => {
      this.close();
    };
  }
  async generateReport() {
    const startMonth = document.getElementById("report-start").value;
    const endMonth = document.getElementById("report-end").value;
    const report = this.buildReport(startMonth, endMonth);
    const folderPath = (0, import_obsidian.normalizePath)(`${this.plugin.settings.monthlyNotesFolder}/Expense Reports`);
    const fileName = `Expense Report ${startMonth} to ${endMonth}.md`;
    const filePath = (0, import_obsidian.normalizePath)(`${folderPath}/${fileName}`);
    try {
      await this.plugin.ensureFolderExists(folderPath);
      const existingFile = this.app.vault.getAbstractFileByPath(filePath);
      if (existingFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existingFile, report);
        new import_obsidian.Notice("Report updated");
      } else {
        await this.app.vault.create(filePath, report);
        new import_obsidian.Notice("Report generated");
      }
      this.close();
    } catch (error) {
      console.error("Error creating report:", error);
      new import_obsidian.Notice("Error creating report");
    }
  }
  buildReport(startMonth, endMonth) {
    let report = `# Expense Report

`;
    report += `**Period:** ${getMoment(startMonth, "YYYY-MM").format("MMM YYYY")} - ${getMoment(endMonth, "YYYY-MM").format("MMM YYYY")}

`;
    report += `**Generated:** ${getMoment().format("YYYY-MM-DD HH:mm")}

---

`;
    const start = getMoment(startMonth, "YYYY-MM");
    const end = getMoment(endMonth, "YYYY-MM");
    const totalAmount = {};
    const totalPaid = {};
    report += `## Monthly Breakdown

`;
    let current = start.clone();
    while (current.isSameOrBefore(end)) {
      const month = current.format("YYYY-MM");
      const recurringExpenses = this.plugin.getExpensesForMonth(month);
      const oneTimeExpenses = this.plugin.getOneTimeExpensesForMonth(month);
      const monthTotals = {};
      const process = (amount, currency, paid) => {
        if (!monthTotals[currency]) monthTotals[currency] = { total: 0, paid: 0 };
        monthTotals[currency].total += amount;
        if (paid) monthTotals[currency].paid += amount;
        if (!totalAmount[currency]) totalAmount[currency] = 0;
        if (!totalPaid[currency]) totalPaid[currency] = 0;
        totalAmount[currency] += amount;
        if (paid) totalPaid[currency] += amount;
      };
      recurringExpenses.forEach((e) => {
        const payment = this.plugin.getPayment(e.id, month);
        process(e.amount, e.currency || "USD", (payment == null ? void 0 : payment.paid) || false);
      });
      oneTimeExpenses.forEach((e) => {
        process(e.amount, e.currency || "USD", e.paid);
      });
      report += `### ${current.format("MMMM YYYY")}

`;
      const currencies = Object.keys(monthTotals).sort();
      if (currencies.length === 0) {
        report += `- No expenses
`;
      } else {
        currencies.forEach((currency) => {
          let symbol = currency + " ";
          if (currency === "USD") symbol = "$";
          else if (currency === "BOB") symbol = "Bs ";
          else if (currency === "EUR") symbol = "\u20AC";
          else if (currency === "GBP") symbol = "\xA3";
          const data = monthTotals[currency];
          const unpaid = data.total - data.paid;
          report += `- **${currency}**: Total: ${symbol}${data.total.toFixed(2)} | Paid: ${symbol}${data.paid.toFixed(2)} | Unpaid: ${symbol}${unpaid.toFixed(2)}
`;
        });
      }
      report += `
`;
      current.add(1, "month");
    }
    report += `## Summary

`;
    const allCurrencies = Object.keys(totalAmount).sort();
    if (allCurrencies.length === 0) {
      report += `No expenses found in this period.

`;
    } else {
      allCurrencies.forEach((currency) => {
        let symbol = currency + " ";
        if (currency === "USD") symbol = "$";
        else if (currency === "BOB") symbol = "Bs ";
        else if (currency === "EUR") symbol = "\u20AC";
        else if (currency === "GBP") symbol = "\xA3";
        const total = totalAmount[currency];
        const paid = totalPaid[currency] || 0;
        const unpaid = total - paid;
        const rate = total > 0 ? (paid / total * 100).toFixed(1) : "0";
        report += `### ${currency}
`;
        report += `- **Total Amount:** ${symbol}${total.toFixed(2)}
`;
        report += `- **Total Paid:** ${symbol}${paid.toFixed(2)}
`;
        report += `- **Total Unpaid:** ${symbol}${unpaid.toFixed(2)}
`;
        report += `- **Payment Rate:** ${rate}%

`;
      });
    }
    report += `## Recurring Expense Breakdown

`;
    const allExpenses = this.plugin.settings.recurringExpenses.filter((e) => !e.archived);
    allExpenses.forEach((expense) => {
      const payments = this.plugin.settings.monthlyPayments.filter(
        (p) => p.expenseId === expense.id && getMoment(p.month, "YYYY-MM").isBetween(start, end, null, "[]")
      );
      const paidCount = payments.filter((p) => p.paid).length;
      const totalCount = payments.length;
      const cur = expense.currency || "USD";
      let symbol = cur + " ";
      if (cur === "USD") symbol = "$";
      else if (cur === "BOB") symbol = "Bs ";
      else if (cur === "EUR") symbol = "\u20AC";
      else if (cur === "GBP") symbol = "\xA3";
      report += `### ${expense.name}

`;
      report += `- Amount: ${symbol}${expense.amount.toFixed(2)}
`;
      report += `- Payment Method: ${expense.paymentMethod}
`;
      report += `- Paid: ${paidCount}/${totalCount} months
`;
      report += `- Total Paid: ${symbol}${(paidCount * expense.amount).toFixed(2)}

`;
    });
    report += `## One-Time Expenses List

`;
    const allOneTime = this.plugin.settings.oneTimeExpenses.filter(
      (e) => getMoment(e.date).isBetween(start, end, null, "[]")
    ).sort((a, b) => a.date.localeCompare(b.date));
    if (allOneTime.length > 0) {
      allOneTime.forEach((e) => {
        const status = e.paid ? "Paid" : "Unpaid";
        const symbol = (e.currency || "USD") === "USD" ? "$" : (e.currency || "USD") === "BOB" ? "Bs " : `${e.currency} `;
        report += `- ${e.date}: **${e.name}** - ${symbol}${e.amount.toFixed(2)} (${status})
`;
      });
    } else {
      report += `No one-time expenses in this period.
`;
    }
    return report;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ExpenseTrackerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [];
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const supportSection = containerEl.createDiv("expense-tracker-setting-support-box");
    new import_obsidian.Setting(supportSection).setName("\u{1F499} Support This Plugin").setHeading();
    supportSection.createEl("p", {
      text: "If you find this plugin helpful, consider supporting its development!"
    });
    const supportLinks = supportSection.createDiv("expense-tracker-setting-links");
    supportLinks.createEl("a", {
      text: "\u{1F4B3} PayPal",
      href: "https://www.paypal.com/paypalme/VictorZenteno",
      cls: "expense-tracker-setting-btn"
    });
    const cryptoBtn = supportLinks.createEl("button", {
      text: "\u{1FA99} USDC/USDT",
      cls: "expense-tracker-setting-btn"
    });
    cryptoBtn.onclick = () => {
      new SupportModal(this.app).open();
    };
    supportLinks.createEl("a", {
      text: "\u2615 Coffee",
      href: "https://buymeacoffee.com/rvzen",
      cls: "expense-tracker-setting-btn"
    });
    supportSection.createEl("p", {
      text: "Your support helps maintain and improve this plugin. Thank you! \u{1F64F}",
      cls: "expense-tracker-text-muted"
    });
    containerEl.createEl("hr", { cls: "expense-tracker-divider" });
    new import_obsidian.Setting(containerEl).setName("Automation & Files").setHeading();
    new import_obsidian.Setting(containerEl).setName("Monthly Notes Folder").setDesc("Folder where monthly expense notes will be created").addText((text) => text.setValue(this.plugin.settings.monthlyNotesFolder).onChange(async (value) => {
      this.plugin.settings.monthlyNotesFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-create Monthly Notes").setDesc("Automatically create monthly notes when a new month begins").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoCreateMonthlyNotes).onChange(async (value) => {
      this.plugin.settings.autoCreateMonthlyNotes = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Status Bar").setDesc("Display unpaid expense count in status bar").addToggle((toggle) => toggle.setValue(this.plugin.settings.showStatusBar).onChange(async (value) => {
      this.plugin.settings.showStatusBar = value;
      await this.plugin.saveSettings();
      if (value && !this.plugin.statusBarItem) {
        this.plugin.statusBarItem = this.plugin.addStatusBarItem();
        this.plugin.updateStatusBar();
      } else if (!value && this.plugin.statusBarItem) {
        this.plugin.statusBarItem.remove();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Monthly Note Template").setDesc("Template for monthly notes. Use {{month}} and {{expenses}} as placeholders.").addTextArea((text) => {
      text.setValue(this.plugin.settings.monthlyNoteTemplate);
      text.inputEl.rows = 10;
      text.inputEl.cols = 50;
      text.onChange(async (value) => {
        this.plugin.settings.monthlyNoteTemplate = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
